name: CI
on:
  pull_request:
  push:
    branches: [ master ]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run : |
          sudo apt-get update
          sudo apt-get install libopencv-dev -qq
      - name: build
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build .

  build-windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run : .\setup_dependencies.bat
      - name: build
        shell: cmd
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build .

  # TODO: The MacOS build is annoyingly slow. Installing OpenCV with homebrew
  # takes forever.
  #
  # build-macos:
  #   runs-on: macOS-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: install dependencies
  #       run: brew install opencv
  #     - name: build
  #       run: |
  #         mkdir build && cd build
  #         cmake ..
  #         cmake --build .
